### ISSUE TITLE
Adjust size and spacing of level 2 headings (in the main body)

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#12]
Something like?

h2, .h2 {
    font-size: 1.6rem;
    margin: 2.5rem 0 1rem;
}

**Comment by ghost** [comment]
I'm going to let @kd-ods recheck this after seeing the affects of #13.
H2 is now 2.3rem
H3 is now 2.0125rem
So we should maybe change both?
