### ISSUE TITLE
Sidebar menu title

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#16]
If possible, add a section title/link to the sidebar menu (to aid with user orientation). E.g. 

## About
  Credits
  Governance

**Comment by ghost** [comment]
Did you have a style in mind for that - I'm guessing Green?

**Comment by ghost** [comment]
Ok, I've pushed something, have a look and comment on the style.

**Comment by kd-ods** [comment]
Great!
