### ISSUE TITLE
Better control of TOCs in sidebar & content

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#17]
I'd like to be able to control the TOC appearing in the sidebar without the TOC appearing within a markup page.

Using the 'hidden' option for the TOC directive hides it within the main page as expected - 

.. toctree::
   :hidden:
   :maxdepth: 1

   credits.md
   governance.md

But it also hides the TOC contents from the sidebar. According to [this Sphinx issue](https://github.com/sphinx-doc/sphinx/issues/1171) there is a way of pulling in those hidden items to the sidebar. (Calling toctree() with includehidden=True.)

Build this [About page](https://github.com/openownership/data-standard/blob/60-refactor-docs/docs/about.md) to see what I mean.

**Comment by ghost** [comment]
So calling toctree() with includehidden=True is an easy change to make to the code and it looks like it does what you want, but there is a problem.

That side menu disappears on narrow screens (mobiles, etc) and there isn't currently a way to get it back. Which means that on mobiles, no-one could navigate to the sub-pages.

One normal UI pattern is a hamburger menu that opens the side menu, but we already have a hamburger menu that opens the top menu, and having 2 hamburger menus would be confusing. Having one hamburger that opened both menus wouldn't really work as I don't think there would be enough screen estate.

Hmm. To discuss ....

**Comment by ghost** [comment]
Done after discussion with @kd-ods.
However "about" page needs a bit more thought about navigation, and what sections should and shouldn't be there.
