### ISSUE TITLE
Deal with 3rd level page navigation

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#19]
At the moment a page in the third tier like:

Data schema > Technical Requirements > Provenance info

... does not have a correctly structured breadcrumb and the page is not bolded etc in the side-panel navigation as you might expect. See the image below:

![image](https://user-images.githubusercontent.com/35495305/39521262-b1b57fea-4e05-11e8-9d01-941dacb1ffdf.png)

**Comment by ghost** [comment]
Done, but leaving this open until this makes it onto RTD properly

**Comment by ghost** [comment]
This in now on RTD.
