### ISSUE TITLE
Style Side Menu 

### ISSUE THREAD

**Issue by ghost** [openownership/data-standard-sphinx-theme#2]
With expand / collapse as in design mockups

**Comment by ghost** [comment]
Done CSS for this. Adding Expand and Collapse will require some JS work.

**Comment by kd-ods** [comment]
Regardless of the accordion effect, can we move the styling towards the [mockup](https://drive.google.com/file/d/14a-kwOUqXoC7qREu6b58fdN_DkjPY5Ar/view?usp=sharing). i.e.:

- light grey background
- white full-width containers for the menu items
- lots of white space
- grey border on the right-hand side

**Comment by ghost** [comment]
Done some work on this - might want to tweak a bit more tho

**Comment by stevenday** [comment]
I'm closing this, as I think it's either done, or out of date. Please re-open if not
