### ISSUE TITLE
Nicely styling in-page TOCs would make navigation more pleasant

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#20]
For example [this page](https://github.com/openownership/data-standard/blob/60-refactor-docs/docs/technical-requirements.md) currently looks like this:

![image](https://user-images.githubusercontent.com/35495305/39626155-b445b13c-4f98-11e8-9366-c14073d213ee.png)

Even just having each list item styled as a big button would improve the look and feel. (TBH I don't think there's an existing style in Matt's work that can be applied here; the [button styles](https://drive.google.com/open?id=1EmJRggrwByWXKl1NG7oMZip8tD13HgKR) aren't quite right.)

Maybe this is something we could ask Matt to look at when he works with us on 12th June?

**Comment by ghost** [comment]
I don't know about just a button - I think if we were going down that route something else would be needed ....

(Also to note this screen-shot has changed - now has underlines)

**Comment by kd-ods** [comment]
I think this improves it a bit:

div.oods-main-document div.toctree-wrapper ul {
    list-style-type: none;
    border-left: 6px solid #eee;
    margin: 50px 0 50px 20%;
}

div.oods-main-document div.toctree-wrapper ul li {
    margin-bottom: 20px;
}

**Comment by ghost** [comment]
Applied - I'm not sure about the % for the top margin measurement tho, but that's a tiny detail for later.

**Comment by stevenday** [comment]
I'm closing this, as I think it's either done, or out of date. Please re-open if not
