### ISSUE TITLE
Update style for inline JSON object names

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#21]
That is: for text marked up like

```statementGroups```

... style it as [Matt recommends](https://drive.google.com/open?id=143gZvXl52Bj7g6OYbkgDCtM8Gjv23oNs).

**Comment by ghost** [comment]
Done, but leaving this open until this makes it onto RTD properly

**Comment by ghost** [comment]
This in now on RTD.
