### ISSUE TITLE
Implement front page layout

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#24]
We'd like to use Bootstrap 'cards' or similar for a front page like this:

https://drive.google.com/file/d/1ylaUl_DwkdS4C77KUfx9bvNWXnEMhelG/view

**Comment by ghost** [comment]
This link is broken and I can't see anything in the folder of design mockups - do we have more on this?

**Comment by kd-ods** [comment]
Sorry, James - try the edited link above.

**Comment by stevenday** [comment]
I'm closing this, as I think it's either done, or out of date. Please re-open if not
