### ISSUE TITLE
Improve link style in main content area

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#25]
Links in the main content area don't stand out enough from the body text. A quick fix would be adding 'text-decoration: underline' to 'oods-main a'. 

For a prettier fix, I can ask Matt to look at this on 12th June.

**Comment by ghost** [comment]
Done, but leaving this open until this makes it onto RTD properly

**Comment by ghost** [comment]
This in now on RTD.
