### ISSUE TITLE
Remove/demote link to 'Edit on GitHub'

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard-sphinx-theme#27]
There is a prominent link on the current theme to 'Edit on GitHub'

Whilst we will be inviting people to contribute to the documentation, we should downplay the idea of making direct documentation pull requests. 

I would suggest for now we either:

(a) Remove the 'Edit on GitHub' link entirely;

(b) Move this to be a low-key link in the footer.

**Comment by ghost** [comment]
This is from original design - tho we can still change it. Comments @kd-ods @ScatteredInk ?

**Comment by kd-ods** [comment]
My preference would be to remove it entirely. If that's not possible then:

* Change the text to 'View on GitHub', and
* Move to footer as a low-key link

**Comment by ghost** [comment]
It's totally possible to remove it entirely if wanted.

**Comment by ghost** [comment]
@kd-ods confirms, removing this
