### ISSUE TITLE
Link style

### ISSUE THREAD

**Issue by M4TEU5** [openownership/data-standard-sphinx-theme#28]
Links are the primary green with the lighter green as for the underline. The underline is set as a border bottom rather than text decoration. This then also fills in on hover.

Here's a code pen
https://codepen.io/anon/pen/KemqBE

**Comment by ghost** [comment]
Done, but I note that on the data page the RFC2119 link isn't highlighting fully, and that may be an accessibility issue.

**Comment by kd-ods** [comment]
@odscjames Can we make the link underline lighter (say #D0EFEF) and bring it as close to the text as possible, in line with the [mockup](https://drive.google.com/file/d/14a-kwOUqXoC7qREu6b58fdN_DkjPY5Ar/view?usp=sharing)?

**Comment by ghost** [comment]
Changed colour. No top/bottom padding but the line height means there is still some space.

**Comment by stevenday** [comment]
I'm closing this, as I think it's either done, or out of date. Please re-open if not
