### ISSUE TITLE
Side Bar

### ISSUE THREAD

**Issue by M4TEU5** [openownership/data-standard-sphinx-theme#32]
I've removed the dark grey background colour introduced heaps more space ( as we don't seem to have that many items across the board (but nowt wrong with scrolling. There is a screenshot on the drive that contains different elements, current section. Hover, sub-section, current selection of a subsection ;)

**Comment by kd-ods** [comment]
The [screenshot is here](https://drive.google.com/file/d/14a-kwOUqXoC7qREu6b58fdN_DkjPY5Ar/view)

**Comment by stevenday** [comment]
I'm closing this, as I think it's out of date with the new theme. Please re-open if not
