### ISSUE TITLE
side bar accordian 

### ISSUE THREAD

**Issue by M4TEU5** [openownership/data-standard-sphinx-theme#34]
Found this animation/transition that would be sweet if we could implement for when the user is opening and closing the menu items in the sidebar. just going for the transition effects here rather than the visuals, something like this would be sweet. Ta

https://codepen.io/matthewhirsch/pen/rLOYGr

**Comment by ghost** [comment]
Thanks - this will be relevant to #2.

**Comment by stevenday** [comment]
I'm closing this as a wontfix, since it's been nearly two years
