### ISSUE TITLE
navbar - yellow underline highlight

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#40]
@odscjames I think this highlight line needs to be wider: at least 4px (not 2px). And the padding under the nav elements (.py-4) reduced to maybe 1rem?

**Comment by ghost** [comment]
Done 4px.

Reducing the padding also reduces the padding under the name top left. Do we want to reduce only underneath or on top to? This needs some thought I think.

**Comment by stevenday** [comment]
Closing as this is probably done in the above commit, but in any case is out of date now with the rebrand.
