### ISSUE TITLE
Improve table styling for schema reference page

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#41]
On [this page](http://standard.openownership.org/en/schema-beta-2/schema/reference.html#interest), the tables are really not very user-friendly.

I'm not sure what our options are for re-formatting and styling these tables are. i.e. how difficult reformatting them as two columns would be eg

Property / Title / Type / Format/ Required | Description
-------------------------------------------------------|----------------
retrievedAt / Retrieved at / string / datetime | If this statement was imported from some external system, include a timestamp indicating when this took place. The statement’s own date should be set based on the source information.

... versus the easy option of styling the tables differently.

**Comment by timgdavies** [comment]
We can update the directives to generate different styles of table (well @bjwebb certainly can).

Might be worth doing a few more design mock-ups - as we've tried various layouts to try and get to something that fits data in well.

**Comment by kd-ods** [comment]
As a first effort, can we just restyle to something like:

![image](https://user-images.githubusercontent.com/35495305/47080585-4dafcd00-d200-11e8-9463-b69c90b8d414.png)

In essence:

- Header row has the signature blue/green colour. (Maybe put headings on different lines to reflect odd-even row contents, as in the above mockup?)
- Even rows have a light grey background, and a heavy top border
- Odd row cells have 20px of bottom padding
- Also (not shown in mockup) I'd get rid of the even row bottom border entirely.

**Comment by ghost** [comment]
As a first pass at the easy bits, how is this?

![Screen Shot 2019-06-27 at 14 21 57](https://user-images.githubusercontent.com/37832009/60269775-02999e00-98e7-11e9-89b1-9ae11bd978cd.png)

Before deploying, I need to check these tables aren't used elsewhere.

**Comment by kd-ods** [comment]
The only substantial issue with that is that 'Name' doesn't appear in the header (i.e. But both property names and titles are listed).

Maybe change 'Title' to 'Property'?

**Comment by ghost** [comment]
As that issue already exists, can I go ahead with merging in the CSS to make the table match the screenshot and then look at other issues raised in this ticket?

I have asked @rhiaro to review https://github.com/openownership/data-standard-sphinx-theme/pull/49

**Comment by kd-ods** [comment]
yes, @odscjames - go for it.

**Comment by ghost** [comment]
https://github.com/openownership/data-standard/pull/229 Adds this to the 0.2 work, in the russian translation branch.

**Comment by kd-ods** [comment]
Fix now visible at http://standard.openownership.org/en/master/schema/reference.html#schema-identifier so closing.
