### ISSUE TITLE
Remove requirements file from this repository

### ISSUE THREAD

**Issue by Bjwebb** [openownership/data-standard-sphinx-theme#58]
As far as I can see [requirements.txt](https://github.com/openownership/data-standard-sphinx-theme/blob/master/requirements.txt) is not used anywhere ([the one from data-standard](https://github.com/openownership/data-standard/blob/master/requirements.txt) is used instead). Can we just remove it?

The same goes for [requirements.in](https://github.com/openownership/data-standard-sphinx-theme/blob/master/requirements.in), but that list might eventually want to move to [setup.py](https://github.com/openownership/data-standard-sphinx-theme/blob/master/setup.py).

**Comment by ghost** [comment]
Yes, I think so.

I think the proper thing to happen here is that the real requirements of this theme move into setup.py

**Comment by Bjwebb** [comment]
Yes.

sphinxcontrib-opendataservices is in the requirements.in, which [has the problems we discussed earlier](https://github.com/OpenDataServices/sphinxcontrib-opendataservices/issues/17#issuecomment-588988597). But, I'm not sure that is really a requirement of this repo!

**Comment by Bjwebb** [comment]
Both requirements files were removed in https://github.com/openownership/data-standard-sphinx-theme/pull/62
