### ISSUE TITLE
Style the highlights class for blockquotes - suggestion below

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#6]
The highlights directive is working, creating HTML like this:
 ````
<blockquote class="highlights">
<div><strong>Beneficial ownership</strong> is the right to some share of a legal entity’s income or assets (ownership) or the right to direct or influence the entity’s activities (control).
</div></blockquote>
````
A style something like this would be good:

blockquote.highlights {
    margin: 2em 0 1em;
    border: solid #fdd106;
    border-width: 1px 1px 1px 10px;
    border-radius: 4px;
    padding: 25px 30px;
    font-size: 120%;
}

**Comment by ghost** [comment]
I tried adding that CSS quickly but it looks a bit odd and I want to check if the design mockups have anything for this.

**Comment by kd-ods** [comment]
Ahh. I thought it would look something like this, and would do for now. (I don't think Matt prepared anything for highlights/blockquotes.) I'll leave it to you and stop interfering!


![image](https://user-images.githubusercontent.com/35495305/39201681-a77e8a68-47e7-11e8-830a-7c039ba5de18.png)

**Comment by ghost** [comment]
If you look at Data Schema -> Specification you'll see a yellow attention highlight box at the top - that came from the design spec. We could just reuse that .... 

_Just add ".highlights" to the https://github.com/openownership/data-standard-sphinx-theme/blob/master/themes/oods/static/oods.css_t file_

> .admonition.attention, .admonition.warning, .highlights {

But I wonder if at this stage a review of the different shout out boxes being used would be good to work out what we are trying to get across to the user with them? Maybe we want to change how we are using some of them, or have a different design on some to differentiate them more?

We have 4 colours in the mockups:

![alerts](https://user-images.githubusercontent.com/37832009/39231950-a1cdad8e-4863-11e8-8f0a-4e60ddde64a2.png)

And no worries, thanks for the input :-)

**Comment by ghost** [comment]
I've styled hightlights directive with yellow for now, we can return to this if wanted.
