### ISSUE TITLE
Use ReadTheDocs' version warning banners

### ISSUE THREAD

**Issue by stevenday** [openownership/data-standard-sphinx-theme#67]
I've recently renamed all the released branches in the standard repo, so that we can take advantage of ReadTheDocs' ability to inject warning banners for viewers of older versions.

This works fine for 0.0.1->0.0.3 which use a standard theme, but doesn't work in 0.1.0 or 0.2.0 which use our custom theme. We need to figure out why (have we lost/overridden a bit of the default layout?). Once they appear, I think we'll also have to style them to fit into the theme better.

In addition, we should remove the warnings we manually added to the 0.0.x versions, as they're now duplicated.

**Comment by kd-ods** [comment]
This was also reported here: https://github.com/openownership/data-standard/issues/76. That issue has been closed as a duplicate.
