### ISSUE TITLE
Top menu: change 'Schemer' to 'Schema'

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#7]
(Is this a theme issue at all? Maybe this is set in the docs markdown somewhere, but I couldn't find it.)

**Comment by ghost** [comment]
I did wonder what a "schemer" was! You can change this easily in https://github.com/openownership/data-standard-sphinx-theme/blob/master/themes/oods/navbar.html or I'll pick this up in a day or two.
