### ISSUE TITLE
Theme issues for 0.4 

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard-sphinx-theme#88]
Sidebar on https://standard.openownership.org/en/main/primer/index.html looks inconsistent across different pages and seems to have shrunk. 

Think the theme docs need updating to reflect renaming of schema -> standard in the docs 

Also the search bar isn't visible

**Comment by kd-ods** [comment]
Hmm - yes. I'm just having a little investigate now.

> Think the theme docs need updating to reflect renaming of schema -> standard in the docs

I don't see 'schema' in the theme. Can you post a screenshot?

**Comment by kathryn-ods** [comment]
I've found it in a few places - see https://github.com/openownership/data-standard-sphinx-theme/pull/90/files where I've edited it

**Comment by kathryn-ods** [comment]
![Image](https://github.com/openownership/data-standard-sphinx-theme/assets/137891030/f317821b-6497-4245-ad45-3fbe68bfe49a)
![Image](https://github.com/openownership/data-standard-sphinx-theme/assets/137891030/cb08667b-7e04-4833-b1b5-96a6ac42ad6c)

**Comment by kd-ods** [comment]
Another issue:

- When on pages in the Data Standard section, the navbar item isn't active (doesn't have the blue line under it).

Kathryn's suggested edit to navbar.html in the theme repo would fix this:

```
            <li class="nav-item{% if currently_in == 'standard' %} active{% endif %} mx-xl-2">
```
