### ISSUE TITLE
Rename Master to Main branch

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard-sphinx-theme#93]
As is now the default for our repos.

**Comment by kathryn-ods** [comment]
Looks like there's 2 branches atm "main" and "master" - might have been an issue with the renaming

**Comment by rhiaro** [comment]
The branches are in sync but I don't have enough permissions on this repo to set the default branch to main. Please could you either upgrade my permissions or change the default branch to main and delete the master branch [here](https://github.com/openownership/data-standard-sphinx-theme/branches)?

**Comment by kathryn-ods** [comment]
Thanks @rhiaro I will get permissions and delete it

**Comment by kathryn-ods** [comment]
@rhiaro @kd-ods we all now have permissions - I have changed main to the default branch, copied the branch protections and deleted master
